# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVKWqfZoc1vdO1qGlKwoEB1G_4_Zn7aS
"""

total_num=int(input('Below is total numer of t-shirt in shop: '))

available_sizes = ['{}{}'.format('X'*1000, size) for size in ['XS', 'S', 'M', 'L', 'XL']]
available_sizes += ['{}{}'.format('X'*i, size) for i in range(1000, -1, -1) for size in ['S', 'M', 'L']]
available_sizes = available_sizes[::-1]

print('below are the avaiable size in shop: ', available_sizes)

request_num=int(input('please tell us the total number of requests: '))

request_size=input('please tell us the size of requests (please use space to split it): ')

def fulfill_requests(request_size, available_sizes):
    for size in request_size:
        if size not in available_sizes:
            print('No available size in shop')
        else:
            print('Yes')
            fulfill_index = available_sizes.index(size)
            
            fulfill_list = available_sizes[fulfill_index:]
            print("Your size {} can be fulfilled with a T-shirt of size {}.".format(size,fulfill_list))
        return True

if fulfill_requests(request_size, available_sizes):
    print('All requests can be fulfilled')
else:
    print('Some requests cannot be fulfilled')